version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./EFCGreenhouse/greenhouse.db:/app/greenhouse.db
    environment:
      - AIVEN_DB_CONNECTION=${AIVEN_DB_CONNECTION}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    external:
      name: greenhouse-network
