version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: greenhouse-backend
    ports:
      - "5001"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MLService__BaseUrl=https://greenhousemlapp.azurewebsites.net
    restart: unless-stopped
