name: Build and deploy container app to Azure Web App - greenhousesep4

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: greenhousesep4.azurecr.io
          username: ${{ secrets.AzureAppService_ContainerUsername_fe95e63d738c4147b311f9ba4adc4c46 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_50e01977bbff463dbbe0342077f5065a }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: greenhousesep4.azurecr.io/greenhouse-backend:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: greenhousesep4
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: greenhousesep4.azurecr.io/greenhouse-backend:${{ github.sha }}
